# Docs: <https://git.io/JP3tm>

blank_issues_enabled: false

contact_links:
  - name: ðŸ—£ Ask a Question, Discuss
    url: https://github.com/tarampampam/random-user-agent/discussions
    about: Feel free to ask anything
