# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: ðŸš€ Deploy the CF challenge test website

on:
  workflow_dispatch: {}
  push:
    branches: [master, main]
    tags-ignore: ['**']
    paths: [website/cf-challenge-test/**, .github/workflows/deploy-website-cf-challenge-test.yml]

concurrency:
  group: ${{ github.ref }}-cf-challenge-test-website
  cancel-in-progress: true

jobs:
  publish:
    name: Publish the site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cloudflare/wrangler-action@v3
        env:
          PROJECT_NAME: random-user-agent-cf-challenge-test
          DIST_DIR: ./website/cf-challenge-test
          CF_BRANCH_NAME: main # to deploy as "Production" environment on Cloudflare Pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command:
            pages deploy ${{ env.DIST_DIR }}
            --project-name=${{ env.PROJECT_NAME }}
            --branch ${{ env.CF_BRANCH_NAME }}
            --commit-dirty=true
