# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: ğŸ§ª Tests

on:
  workflow_dispatch: {}
  push:
    branches: [master, main]
    tags-ignore: ['**']
    paths-ignore: ['**.md', 'website/**', 'static/**']
  pull_request:
    paths-ignore: ['**.md', 'website/**', 'static/**']

concurrency:
  group: ${{ github.ref }}-tests
  cancel-in-progress: true

env: {FORCE_COLOR: 'true'}

jobs:
  gitleaks:
    name: ğŸ” Check for GitLeaks
    runs-on: ubuntu-latest
    steps:
      - {uses: actions/checkout@v4, with: {fetch-depth: 0}}
      - uses: gacts/gitleaks@v1

  unit-tests:
    name: ğŸ§ª Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - {uses: gacts/setup-node-with-cache@v1, with: {node-version: 21}}
      - run: npm install
      - run: npm run test

  eslint:
    name: ğŸ§¹ Run code linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - {uses: gacts/setup-node-with-cache@v1, with: {node-version: 21}}
      - run: npm install
      - run: npm run lint

  build:
    name: ğŸ—ï¸ Build extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - {uses: gacts/setup-node-with-cache@v1, with: {node-version: 21}}
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with: {name: dist-zip, path: dist/*.zip, if-no-files-found: error, retention-days: 30}

#  build:
#    name: Try to build
#    runs-on: ubuntu-latest
#    env: {FORCE_COLOR: 'true'}
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: actions/setup-node@v4
#        with: {node-version: '20'}
#
#      - uses: actions/cache@v4
#        id: yarn-cache
#        with:
#          path: '**/node_modules'
#          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: ${{ runner.os }}-yarn-
#
#      - if: steps.yarn-cache.outputs.cache-hit != 'true'
#        run: yarn install --frozen-lockfile --no-progress --non-interactive
#
#      - run: yarn build
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: extension-dist
#          path: dist.zip
#          if-no-files-found: error
#          retention-days: 1
#
#  addons-linter:
#    name: Run addon linter (mozilla)
#    runs-on: ubuntu-latest
#    needs: [build]
#    env: {FORCE_COLOR: 'true'}
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: actions/download-artifact@v4
#        with:
#          name: extension-dist
#          path: dist
#
#      - uses: actions/setup-node@v4
#        with: {node-version: '20'}
#
#      - run: yarn global add addons-linter
#
#      - run: addons-linter ./dist/dist.zip
